student_model: openmath/openmath-nemotron-7b-awq
reference_model: openmath/openmath-nemotron-7b-awq
output_dir: runs/dpo
dataset_path: data/preferences/train.jsonl
eval_dataset_path: data/preferences/valid.jsonl
subset_size: null
filter_max_prompt_length: 2000
learning_rate: 1.0e-5
beta: 0.1
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 8
num_train_epochs: 1
warmup_steps: 200
weight_decay: 0.01
logging_steps: 50
save_steps: 500
evaluation_strategy: steps
bf16: true
fp16: false
device_map: auto
reference_device_map: auto
report_to: []
seed: 42
lora:
  r: 16
  lora_alpha: 32
  target_modules:
    - q_proj
    - v_proj
  lora_dropout: 0.05
  bias: none
